# Generated by Django 5.0.4 on 2024-05-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(null=True)),
                ('password', models.TextField(null=True)),
                ('negara_asal', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
